[world]
name = "Genshin TCG"
description = "Genshin TCG is a trading card game based on the popular game Genshin Impact."
cover_uri = "https://assets.starksailor.net/starksailor/upload/cover.png"
icon_uri = "https://assets.starksailor.net/starksailor/upload/icon.png"
website = "https://starksailor.net/"
seed = "genshin_tcg"

[world.socials]
github = "https://github.com/Meadovv/genshin-tcg"

[namespace]
default = "genshin_tcg"

[env]
rpc_url = ""
account_address = ""
private_key = ""
# world_address = ""   # Update this line with your world address

[writers]
"stark_sailor" = ["stark_sailor-actions"]