[package]
name = "genshin_tcg_v1"
version = "1.0.0"
cairo-version = "=2.8.4"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
starknet = "2.8.4"
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.2" }
alexandria_ascii = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "e1b0805" } # v2.7.0

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.2" }

[features]
default = []

[profile.dev]
[profile.release]